version: "3.10"

services:

  bot:
    build: .
    command: /code/start.sh
    volumes:
      - .:/code
    ports:
      - "8008:8008"
    env_file:
      - .env
    networks:
      - shared_network

# This network must be created manually before running docker-compose up
networks:
  shared_network:
    external: true
